version: '3'
services:

  db:
    image: postgres
    volumes:
      - ./db/pgdata:/pgdata
    ports:
      - "5432:5432"
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      PGDATA: /pgdata

  api:
    build:
      context: ./api
      args:
        app_env: ${APP_ENV}
    image: go-challenge
    ports:
      - "3000:3000"
    links:
      - db
